name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      # Generate personal stats card
      - name: Generate personal stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=guogenglin&show_icons=true&count_private=true&layout=compact&hide=prs&theme=vue&transparent=true&hide_border=true
          path: profile/stats-guogenglin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generate personal top languages card
      - name: Generate personal top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=guogenglin&show_icons=true&count_private=true&layout=compact&hide=prs&theme=vue&transparent=true&hide_border=true
          path: profile/top-langs-guogenglin.svg
          token: ${{ secrets.GITHUB_TOKEN }}
